# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_attenders',
            field=models.ManyToManyField(related_name='job_attenders', to='first_app.User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_poster', to='first_app.User'),
        ),
    ]
