# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20180726_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('travel_start_date', models.DateField()),
                ('travel_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='first_app.User')),
                ('join', models.ManyToManyField(related_name='joiner', to='first_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_attenders',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
