# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20180726_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Travel',
            new_name='Trip',
        ),
    ]
