# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20180726_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planner', to='first_app.User')),
                ('join', models.ManyToManyField(related_name='joiner', to='first_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='join',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
